In [1]:
print((3,)+(4,))
print(("apple")+("banana"))

(3, 4)
applebanana


In [3]:
temps = [28, 31, 33, 35, 27, 26, 25]
values = list(temps)
values[3] = 39 # values 리스트 변경
print(temps)

[28, 31, 33, 35, 27, 26, 25]


In [4]:
lst = [1, 2, 3, 4, 5, 6, 7, 8]
lst[::2] = [99, 99, 99, 99]
print(lst)
lst = [1, 2, 3, 4, 5, 6, 7, 8]
lst[:] = [ ]
print(lst)

[99, 2, 99, 4, 99, 6, 99, 8]
[]


In [5]:
rows = 3
cols = 5
s=[]
for row in range(rows):
    s += [[0]*cols]
print("s =", s)
# 2차원 리스트 합침

s = [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


In [6]:
list1 = [1, 2, 3, 4, 5]
list2 = [3, 4, 5, 6, 7]
print(set(list1) & set(list2))
print(set(list1) - set(list2))

{3, 4, 5}
{1, 2}


In [7]:
dic = {i:str(i)for i in [1, 2, 3, 4, 5]}
print(dic)

{1: '1', 2: '2', 3: '3', 4: '4', 5: '5'}


In [8]:
import numpy as np
scores = np.array([[99, 93, 60], [98, 82, 93],
                   [93, 65, 81], [78, 82, 81]])
print(scores.mean(axis=1))

[84.         91.         79.66666667 80.33333333]


In [10]:
np_array = np.array([[ 1, 2, 3, 4], [5, 6, 7, 8], [ 9, 10, 11, 12],
[13, 14, 15, 16]])

print(np_array[::2])
print(np_array[::2][::2]) # Nested 인덱싱, 슬라이싱, 첫 슬라이싱: 0행, 2행 선택, 두 번째 슬라이싱: 그 중 0행 선택
print(np_array[::2, ::2]) # 행 슬라이싱: 0행, 2행 선택, 열 슬라이싱: 0열 2열 선택

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[1 2 3 4]]
[[ 1  3]
 [ 9 11]]


In [11]:
import numpy as np

players = np.zeros((100, 3))
#print(players)
players[:, 0] = 10 * np.random.randn(100) + 175
players[:, 1] = 10 * np.random.randn(100) + 70
players[:, 2] = np.floor(10 * np.random.randn(100)) + 22 # 나이는 정수로 #players[:, 2] = 10 * np.random.randn(100) + 22
#print(players)

heights = players[:, 0]
print('신장 평균값:', np.mean(heights))
print('신장 중앙값:', np.median(heights))

weights = players[:, 1]
print('체중 평균값:', np.mean(weights))
print('체중 중앙값:', np.median(weights))
ages = players[:, 2]
print('나이 평균값:', np.mean(ages))
print('나이 중앙값:', np.median(ages))

신장 평균값: 176.89290763454596
신장 중앙값: 177.72480920357918
체중 평균값: 70.85500213376173
체중 중앙값: 70.62909515547344
나이 평균값: 22.55
나이 중앙값: 23.0


In [13]:
import numpy as np

y = np.arange(12)
print(y.shape)
print(y.reshape(6, -1))
print(y.flatten())

(12,)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
