### 리스트

In [1]:
# 리스트 방문
temps = [28, 31, 33, 35, 25] 

for i in range(len(temps)):
	print(temps[i], end='  ')
# 	print(temps[i])

28  31  33  35  25  

In [2]:
temps = [28, 31, 33, 35, 27, 26, 25] 

for element in temps:
	print(element, end=', ')

28, 31, 33, 35, 27, 26, 25, 

In [3]:
# zip() 함수
questions = ['name', 'quest', 'color', 'name2']
answers = ['Kim', '파이썬', 'blue']
for q, a in zip(questions, answers):
	print(f"What is your {q}?  It is {a}")

What is your name?  It is Kim
What is your quest?  It is 파이썬
What is your color?  It is blue


In [4]:
# append() -> 순서대로 뒤에 항목이 붙음
heroes = [ ] 				  # 공백 리스트를 생성한다. 
heroes.append("아이언맨")	    # 리스트에 ”아이언맨“을 추가한다. 
heroes.append("토르")          # 리스트에 ”토르“를 추가한다.
heroes.append("스파이더맨")			 
print(heroes)

['아이언맨', '토르', '스파이더맨']


In [5]:
# insert() -> 인덱스 지정, 해당 인덱스에 항목 삽입
heroes = ["아이언맨", "토르", "헐크"] 
heroes.insert(1, "스파이더맨") 
print(heroes)

['아이언맨', '스파이더맨', '토르', '헐크']


In [6]:
# 리스트 탐색
heroes = ["아이언맨", "토르", "헐크", "스칼렛 위치", "헐크"]
n = heroes.index("헐크")		# n은 2가 된다(첫 번째 요소 출력)
print(n)

if "스파이더맨" in heroes:
    print(heroes.index("스파이더맨"))

heroes = ["아이언맨", "토르", "헐크", "스칼렛 위치", "헐크"]
n = heroes.index("헐크", 3)		# 헐크를 찾는데 3부터 시작하라. n은 4가 된다. 
print(n)

2
4


In [7]:
# 요소 삭제하기
heroes = ["아이언맨", "토르", "헐크"]
# print(heroes.pop(1))         # assign index
# print(heroes.pop())
heroes.remove("스파이더맨")     # assign value
print(heroes)

ValueError: list.remove(x): x not in list

In [8]:
heroes = ["아이언맨", "토르", "헐크"]

if "토르" in heroes:
	heroes.remove("토르")
print(heroes)

['아이언맨', '헐크']


In [9]:
heroes = ["아이언맨", "토르", "헐크"]
if "스파이더맨" in heroes:
	heroes.remove("스파이더맨")
print(heroes)

heroes.remove("홍길동")

['아이언맨', '토르', '헐크']


ValueError: list.remove(x): x not in list

In [10]:
#리스트 항목의 최대 및 최소값
values = [1, 2, 3, 4, 5, 6, 7, 8, 9, 100]
print(min(values))		
print(max(values))		

1
100


In [11]:
# 리스트 정렬: 메소드 이용
a = [3, 2, 1, 5, 4]
a.sort()
print(a)			

[1, 2, 3, 4, 5]


In [12]:
a = [3, 2, 1, 5, 4]
a.sort()
a

[1, 2, 3, 4, 5]

In [13]:
heroes = ['아이언맨','헐크','토르']
heroes.sort()
print(heroes)

['아이언맨', '토르', '헐크']


In [14]:
# 역순 정렬
a = [3, 2, 1, 5, 4]
a.sort(reverse=True)
print(a)

[5, 4, 3, 2, 1]


In [15]:
# 리스트 정렬: 내장함수 이용
numbers = [10, 3, 7, 1, 9, 4, 2, 8, 5, 6]
ascending_numbers =sorted(numbers)
print(ascending_numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [16]:
# 내장함수 예
numbers = [10, 20, 30, 40, 500]

print("합=", sum(numbers))		# 항목의 합계를 계산한다. 
print("최대값=", max(numbers))		# 가장 큰 항목을 반환한다. 
print("최소값=", min(numbers))		# 가장 작은 항목을 반환한다.

합= 600
최대값= 500
최소값= 10


In [17]:
# 리스트에서 항목을 랜덤으로 선택
import random

numberList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print("랜덤하게 선택한 항목=", random.choice(numberList))

랜덤하게 선택한 항목= 5


In [18]:
import random
movie_list = ["Citizen Kane", "Singin' in the Rain", "Modern Times",
              "Casablanca", "City Lights"]

item = random.choice(movie_list)
print ("랜덤하게 선택한 항목=", item)

랜덤하게 선택한 항목= Casablanca


In [52]:
# lab: 4성적처리 프로그램
STUDENTS = 5 
lst = [] 
count=0

for i in range(STUDENTS):
    value = int(input("성적을 입력하시오: "))
    lst.append(value)
print(lst)

print("\n성적평균=", sum(lst) / len(lst))
print("최대점수=", max(lst))
print("최소점수=", min(lst))

for score in lst:
    if score >= 80:
        count += 1
print("80점 이상=", count)

[112, 22, 34, 78, 99]


TypeError: object of type 'int' has no len()

In [20]:
# Lab: 리스트에서 두번째로 큰 수 찾기 1
list1 = [1, 2, 3, 4, 15, 99] 
list1.sort()
print(list1) 
  
# 뒤에서 두 번째 요소를 출력한다. 
print("두 번째로 큰 수=", list1[-2]) 

[1, 2, 3, 4, 15, 99]
두 번째로 큰 수= 15


In [21]:
# Lab: 리스트에서 두번째로 큰 수 찾기 2
list1 = [1, 2, 3, 4, 15, 99] 
 
# 제일 큰 수는 삭제한다. 
list1.remove(max(list1)) 
print(list1)

# 그 다음으로 큰 수를 출력한다. 리스트는 변경되었다. 
print("두 번째로 큰 수=", max(list1)) 
#print(list1)

[1, 2, 3, 4, 15]
두 번째로 큰 수= 15


In [22]:
# Lab: 콘테스트 평가(1)
scores = [10.0, 9.0, 8.3, 7.1, 3.0, 9.0]
print("제거 전", scores)

scores.remove(max(scores))
print(scores)
scores.remove(min(scores))
print("제거 후", scores)

제거 전 [10.0, 9.0, 8.3, 7.1, 3.0, 9.0]
[9.0, 8.3, 7.1, 3.0, 9.0]
제거 후 [9.0, 8.3, 7.1, 9.0]


In [23]:
# Lab: 콘테스트 평가(2)
scores = [10.0, 9.0, 8.3, 7.1, 3.0, 9.0]
print("제거 전", scores)
scores.sort() 
print(scores)

new_scores = scores[1:-1] 
print("제거 후", new_scores)

제거 전 [10.0, 9.0, 8.3, 7.1, 3.0, 9.0]
[3.0, 7.1, 8.3, 9.0, 9.0, 10.0]
제거 후 [7.1, 8.3, 9.0, 9.0]


In [24]:
# Lab: 리스트로 스택 흉내내기
stack = []

for i in range(3) :
    f = input("과일을 입력하시오: ")
    stack.append(f)
    print(stack)

for i in range(3) :
    print(stack.pop())   # 맨 뒤에 것 꺼냄

['']
['', '']
['', '', '']





In [25]:
# 리스트 합병
heroes1 = ["아이언맨", "토르"]
heroes2 = ["헐크", "스칼렛 위치"]
avengers = heroes1 + heroes2  
print(avengers) 		

['아이언맨', '토르', '헐크', '스칼렛 위치']


In [26]:
numbers = [1, 2, 3, 4] * 5 	
print(numbers)

numbers = [0] * 5 
print(numbers)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
[0, 0, 0, 0, 0]


In [27]:
# 리스트 비교
list1 = [1, 2, 3]
list2 = [1, 2, 3]
print(list1 == list2)		# True

list1 = [0, 4, 5]
list2 = [1, 2, 3]
print(list1 > list2)  		# 전체 요소가 참일 때 참

True
False


In [28]:
# 리스트 복사: 얕은 복사
temps = [28, 31, 33, 35, 27, 26, 25] 
values = temps

print(temps)			# temps 리스트 출력
values[3] = 100			# values 리스트 변경
print(temps)			# temps 리스트가 변경되었다. 

[28, 31, 33, 35, 27, 26, 25]
[28, 31, 33, 100, 27, 26, 25]


In [29]:
# 리스트 복사: 깊은 복사
temps = [28, 31, 33, 35, 27, 26, 25] 
values = list(temps)

print(temps)			# temps 리스트 출력
values[3] = 39			# values 리스트 변경
print(temps)
print(values)

[28, 31, 33, 35, 27, 26, 25]
[28, 31, 33, 35, 27, 26, 25]
[28, 31, 33, 39, 27, 26, 25]


In [30]:
# 리스트 슬라이싱
numbers = [10, 20, 30, 40, 50, 60, 70, 80, 90]
sublist = numbers[1:7]
print(sublist)

print(numbers[:3])	

print(numbers[3:])	

print(numbers[:])	

new_numbers = numbers[:]  ## 깊은 복사
print(new_numbers)

[20, 30, 40, 50, 60, 70]
[10, 20, 30]
[40, 50, 60, 70, 80, 90]
[10, 20, 30, 40, 50, 60, 70, 80, 90]
[10, 20, 30, 40, 50, 60, 70, 80, 90]


In [31]:
# 리스트 고급 슬라이싱
numbers = [10, 20, 30, 40, 50, 60, 70, 80, 90]
sublist = numbers[2:7:3]
print(sublist)

[30, 60]


In [32]:
# 리스트를 역순으로 바꿈
numbers = [10, 20, 30, 40, 50, 60, 70, 80, 90]
numbers[::-1]

[90, 80, 70, 60, 50, 40, 30, 20, 10]

In [33]:
# 리스트 변경
lst = [1, 2, 3, 4, 5, 6, 7, 8]
lst[0:3] = ['white', 'blue', 'red']
print(lst)

lst = [1, 2, 3, 4, 5, 6, 7, 8]
lst[::2] = [99, 99, 99, 99]
print(lst)

lst = [1, 2, 3, 4, 5, 6, 7, 8]
lst[:] = [ ]
print(lst)

numbers = list(range(0, 10))
print(numbers)
del numbers[-1]
print(numbers)

['white', 'blue', 'red', 4, 5, 6, 7, 8]
[99, 2, 99, 4, 99, 6, 99, 8]
[]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [34]:
# 문자열과 리스트
s = "Monty Python"
print(s[1])			    # M
print(s[6:10])			# Pyth
print(s[-12:-7])		# Monty

o
Pyth
Monty


In [35]:
# 리스트 슬라이싱
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
reversed = numbers[::-3]
print(reversed)

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
numbers[2:] = [ ]
print(numbers)

[10, 7, 4, 1]
[1, 2]


In [36]:
# 불변 객체의 함수 전달 
def func1(x):
    x = 42
    print("x=", x," id=", id(x))

y = 10
func1(y)
print("y=",y," id=", id(y))

x= 42  id= 4378845360
y= 10  id= 4378844336


In [37]:
# 변경 가능 객체의 함수 전달
def func2(list):
    list[0] = 99
    list[1] = 100
   
values = [0, 1, 1, 2, 3, 5, 8]
func2(values)
print(values)

[99, 100, 1, 2, 3, 5, 8]


In [38]:
# Lab: 리스트 변경 함수
salaries = [200, 250, 300, 280, 500]

def modify(values, factor):
    for i in range(len(values)):
        values[i] = values[i] * factor
        
#def modify(values, factor):
#    for e in values:
#        e = e * factor
#        print(e)

print("인상 전", salaries)
modify(salaries, 1.5)
print("인상 후", salaries)

인상 전 [200, 250, 300, 280, 500]
인상 후 [300.0, 375.0, 450.0, 420.0, 750.0]


In [39]:
# 리스트 함축
squares = []
for x in range(10):
    squares.append(x*x)
print(squares)

squares = [x*x for x in range(10)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [40]:
# 리스트 함축: 조건 사용할 수 있음
squares = []
for x in range(10):
    if x % 2 == 0:
        squares.append(x*x)
print(squares)

squares = [x*x for x in range(10) if x % 3 == 0]
print(squares)

[0, 4, 16, 36, 64]
[0, 9, 36, 81]


In [41]:
# 다양한 리스트 함축 예

prices = [135, -545, 922, 356, -992, 217]
mprices = [i if i > 0 else 0 for i in prices]
print(mprices)

words = ["All", "good", "things", "must", "come", "to", "an", "end."]
letters = [w[-1] for w in words]
print(letters)

numbers = [x + y for x in ['a','b','c'] for y in ['x','y','z']]
print(numbers)

x = ['a'] 
y = ['x']
print(x + y)

[135, 0, 922, 356, 0, 217]
['l', 'd', 's', 't', 'e', 'o', 'n', '.']
['ax', 'ay', 'az', 'bx', 'by', 'bz', 'cx', 'cy', 'cz']
['a', 'x']


In [42]:
# Lab: 리스트 함축
numbers = [x for x in range(100) if x % 2 == 0 and x % 5 == 0]
print(numbers)

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]


In [43]:
# 2차원 리스트 생성 (리스트 안의 리스트)

s = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
print(s)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]


In [44]:
s = [[1, 2, 3, 4, 5], 
     [6, 7, 8, 9, 10], 
	 'kim', 
	 12]
print(s)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], 'kim', 12]


In [45]:
import numpy as np

s = [[1, 2, 3, 4, 5],[6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
	 
s1 = np.array(s)
print(s1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [46]:
# 2차원 리스트의 동적 생성 
rows = 3
cols = 5

s = [ ]
for row in range(rows): 
	s += [[0]*cols]		# 2차원 리스트 합침 
print("s =", s)

# 1차원 리스트 합침
s = [ ]
for row in range(rows): 
	s += [0]*cols		# 1차원 리스트 합침 
print("s =", s)

s = [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]
s = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [47]:
# 리스트 함축 이용
rows = 3
cols = 5

s = [([0] * cols) for row in range(rows)]
print("s =", s)

s = [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


In [48]:
# 2차원 리스트 요소 접근
s = [[1, 2, 3, 4, 5] ,
	 [6, 7, 8, 9, 10], 
	 [11, 12, 13, 14, 15]]

rows = len(s)    # 행과 열의 개수를 구함
cols = len(s[0])

for r in range(rows):
	for c in range(cols):
		print(s[r][c], end=", ")
	print()

1, 2, 3, 4, 5, 
6, 7, 8, 9, 10, 
11, 12, 13, 14, 15, 


In [49]:
# 2차원 리스트를 함수로 넘기기
s = [[1, 2, 3, 4, 5] ,
	 [6, 7, 8, 9, 10], 
	 [11, 12, 13, 14, 15]]

def sum(numbers) :
    total = 0
    for i in range(len(numbers)) :
        for j in range(len(numbers[0])) :
             total = total + numbers[i][j]
    return total

print(sum(s))

120


In [50]:
# 체커 보드 패턴 만들기
table = [ ]

# 2차원 리스트를 화면에 출력한다.
def printList(mylist):
    for row in range(len(mylist)): 
        for col in range(len(mylist[0])): 
            print(mylist[row][col], end=" ")
        print()

# 2차원 리스트를 체커보드 형태로 초기화한다. 
def init(mylist):
    for row in range(len(mylist)): 
        for col in range(len(mylist[0])): 
            if (row+col)%2 == 0:
                table[row][col] = 1

# 2차원 리스트를 생성한다. 
for row in range(10): 
    table += [[0]*10]
print(table)

init(table)
printList(table)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
1 0 1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 0 1 


In [1]:
# 2차원 리스트 함축
matrix = [[i for i in range(6)] for _ in range(6)]
print(matrix)

matrix = [[0, 0, 0], [1, 1, 1], [2, 2, 2]]
result = [num for row in matrix for num in row]
print(result)

matrix = [[0, 0, 0], [1, 1, 1], [2, 2, 2]]
result = []
for row in matrix:
    for num in row:
        result.append(num)
print(result)

matrix = [[0, 0, 0], [1, 1, 1], [2, 2, 2]]
result = []
for row in matrix:
    print("=>", row)
    for num in row:
        print(num)
        result.append(num)
        print(result)

[[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]]
[0, 0, 0, 1, 1, 1, 2, 2, 2]
[0, 0, 0, 1, 1, 1, 2, 2, 2]
=> [0, 0, 0]
0
[0]
0
[0, 0]
0
[0, 0, 0]
=> [1, 1, 1]
1
[0, 0, 0, 1]
1
[0, 0, 0, 1, 1]
1
[0, 0, 0, 1, 1, 1]
=> [2, 2, 2]
2
[0, 0, 0, 1, 1, 1, 2]
2
[0, 0, 0, 1, 1, 1, 2, 2]
2
[0, 0, 0, 1, 1, 1, 2, 2, 2]
