## 넘파이

#### 리스트와 넘파이 배열의 차이

In [ ]:
mid_scores = [10, 20, 30]    # 파이썬 리스트 객체
final_scores = [70, 80, 90]  # 파이썬 리스트 객체
mid_scores

In [52]:
total = mid_scores + final_scores    # 원소간의 합이 아닌 리스트를 연결함
total
print('시험성적의 합계 :', total)    
print('시험성적의 평균 :', total/2) 

시험성적의 합계 : [ 70  90 110]
시험성적의 평균 : [35. 45. 55.]


#### 넘파이의 별칭과 배열 연산하기

In [53]:
import numpy as np   # 앞으로 numpy의 별명을 np로 한다

In [54]:
# array() 함수에 파이썬 리스트를 전달하면 넘파이 배열이 생성됨
mid_scores  = np.array([10, 20, 30])
final_scores = np.array([60, 70, 80])
mid_scores

array([10, 20, 30])

In [55]:
total = mid_scores + final_scores
print('시험성적의 합계 :', total)    # 각 요소별 합계가 나타난다
print('시험성적의 평균 :', total/2)  # 모든 요소를 2로 나눈다

시험성적의 합계 : [ 70  90 110]
시험성적의 평균 : [35. 45. 55.]


In [56]:
# 넘파이 내장 함수
A = np.array([0, 1, 2, 3])
10 * np.sin(A)      # 각 항목에 대해서 sin값 적용

array([0.        , 8.41470985, 9.09297427, 1.41120008])

In [57]:
# 다양한 넘파이 함수 적용
scores = np.array([[99, 93, 60], [98, 82, 93], 
                   [93, 65, 81], [78, 82, 81]])
scores

array([[99, 93, 60],
       [98, 82, 93],
       [93, 65, 81],
       [78, 82, 81]])

In [58]:
print(scores.min())             # 전체 중 min
print(scores.min(axis=0))       # 과목별 min
print(scores.min(axis=1))       # 학생별 min

print(scores.max())
print(scores.mean())
print(scores.std())
print(scores.var())

60
[78 65 60]
[60 82 65 78]
99
83.75
11.769487386175038
138.52083333333334


In [ ]:
# 행이나 열단위로 계산 가능
print(scores.mean(axis=0))
print(scores.mean(axis=1))

In [ ]:
# Lab: ndarray 객체 생성 및 속성
a = np.array(range(1, 11))
b = np.array(range(10, 101, 10))
 
print(a)
print(b)
print(a + b); print(b - a); print(a * b); print(a / b)

#### 넘파이의 핵심 다차원배열(ndarray)

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4])       # 넘파이 ndarray 객체의 생성
a.shape      # a 객체의 형태(shape)

In [ ]:
a.ndim      # 차원 확인

In [ ]:
a.dtype     # 데이터 타입 확인

In [ ]:
a.itemsize   # 객체 내부 자료형이 차지하는 메모리 크기(byte)

In [ ]:
a.size   # 객체의 항목의 수

##### Lab: Ndarray 객체 생성 및 속성

In [ ]:
import numpy as np

# 실습 1
array_a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('실습 1 : array_a =', array_a)

# 실습 2
array_b = np.array(range(10))
print('실습 2 : array_b =', array_b)

print(array_a + array_b)

# 실습 3
array_c = np.array(range(0, 10, 2))
print('실습 3 : array_c =', array_c)

# 실습 4
print('실습 4: ')
print('array_c의 shape :', array_c.shape)
print('array_c의 ndim :', array_c.ndim)
print('array_c의 ctype :', array_c.dtype)
print('array_c의 size :', array_c.size)
print('array_c의 itemsize :',array_c.itemsize)

#### 넘파이 배열 연산

In [34]:
import numpy as np
salary = np.array([220, 250, 230])
salary

array([220, 250, 230])

In [35]:
salary = salary + 100
# salary += 100
print(salary)

[320 350 330]


In [36]:
salary = np.array([220, 250, 230])
salary = salary * 2
print(salary)

[440 500 460]


In [37]:
salary = np.array([220, 250, 230]) 
salary = salary * 2.1           # 실수 값 적용 가능함
print(salary)

[462. 525. 483.]


#### Note
넘파이 배열 안에는 동일한 타입의 데이터만 저장할 수 있다. 즉 정수면 정수, 실수면 실수만을 저장할 수 있다. 파이썬 리스트처럼 여러 가지 타입을 섞어서 저장할 수 없다. 만약 넘파이 배열에 여러 가지 타입을 섞어서 전달하면 넘파이는 이것을 전부 문자열로 변경한다. 

In [38]:
tangled = np.array([ 100, 'test', 3.0, False])
print(tangled)

['100' 'test' '3.0' 'False']


##### Lab: BMI 계산

In [39]:
import numpy as np
heights = [1.83, 1.76, 1.69, 1.86, 1.77, 1.73]      # 여기까지는 그냥 python array
weights = [ 86,   74,   59,   95,   80,   68 ]

np_heights = np.array(heights)
np_weights = np.array(weights)

bmi = np_weights/(np_heights**2)
print(bmi)

print(bmi[bmi > 25])   # BMI가 25를 넘는 사람의 BMI만을 출력

[25.68007405 23.88946281 20.65754    27.45982194 25.53544639 22.72043837]
[25.68007405 27.45982194 25.53544639]


#### 인덱싱과 슬라이싱

In [40]:
import numpy as np
scores = np.array([88, 72, 93, 94, 89, 78, 99]) 

In [41]:
scores[2]

93

In [42]:
scores[-1]

99

In [43]:
scores[1:4]     # 두번째, 세번째, 네번째 항목을 슬라이싱 함

array([72, 93, 94])

In [44]:
scores[3:]      # 마지막 인덱스를 생략하면 끝까지 감

array([94, 89, 78, 99])

In [45]:
scores[4:-1]      # 마지막 인덱스 -1을 사용

array([89, 78])

#### 논리적 인덱싱

In [46]:
ages = np.array([18, 19, 25, 30, 28])

In [47]:
y = ages > 20
y

array([False, False,  True,  True,  True])

In [48]:
ages[ages > 20]
#ages[y]

array([25, 30, 28])

#### 2차원 배열

In [49]:
# 파이썬의 2차원 리스트 "리스트의 리스트", 행렬이 아님

y = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]  
y 

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [50]:
# 넘파이를 이용한 2차원 배열: 행렬이며, 행렬에 관련된 연산을 수행할 수 있다.
import numpy as np 

np_array = np.array(y) 
np_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
np_array[0][2]

3

#### 넘파이 스타일의 배열 인덱싱

In [61]:
np_array = np.array([[1,2,3], [4,5,6], [7,8,9]]) 
np_array[0, 2]

3

In [ ]:
np_array[0, 0]

In [ ]:
np_array[2, -1]

In [ ]:
np_array[0, 0] = 12   # ndarray의 첫 항목을 변경함
np_array

In [ ]:
# 넘파이 배열의 모든 항목은 동일한 자료형이어야 함
np_array[2, 2] = 1.234  # 마지막 요소의 값을 실수로 변경하려고 하면 정수로 저장
np_array

#### 넘파이 스타일의 2차원 배열 슬라이싱

In [ ]:
# 넘파이 슬라이싱은 큰 행렬에서 작은 행렬을 끄집어 내는 것과 같음
np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
np_array[0:2, 1:3]

In [ ]:
np_array[0]

In [ ]:
np_array[1, 1:3]

In [ ]:
# 파이썬 리스트 슬라이싱과 넘파이 스타일 슬라이싱 비교
np_array = np.array([[ 1,  2,  3,  4], 
                     [ 5,  6,  7,  8], 
                     [ 9, 10, 11, 12], 
                     [13, 14, 15, 16]]) 
print(np_array[::2])
print(np_array[::2][::2]) # Nested 인덱싱, 슬라이싱, 첫 슬라이싱: 0행, 2행 선택, 두 번째 슬라이싱: 그 중 0행 선택
print(np_array[::2, ::2])  # 행 슬라이싱: 0행, 2행 선택, 열 슬라이싱: 0열 2열 선택
print(np_array[1::2])
print(np_array[1::2, 1::2])

#### 2차원 배열의 논리적 인덱싱

In [ ]:
np_array = np.array([[1,2,3], [4,5,6], [7,8,9]]) 
np_array > 5

In [ ]:
np_array[np_array > 5]

In [ ]:
np_array[:, 2]   # 세번째 열 추출

In [ ]:
np_array[:, 2] > 5

In [ ]:
np_array[:] % 2 == 0  # 짝수 확인

In [ ]:
np_array[np_array[:] % 2 == 0]  # 짝수 찾기

##### Lab: 2차원 배열 연습

In [ ]:
# c 문자 갯수 찾기
import numpy as np
x = np.array( [['a', 'b', 'c', 'd'],
               ['c', 'c', 'g', 'h']])

print([x == 'c'])
print(x[x == 'c'])

In [ ]:
mat_a = np.array([[10, 20, 30], [10, 20, 30]])
mat_b = np.array([[2, 2, 2], [1, 2, 3]])

print(mat_a - mat_b)
print(mat_a + mat_b)
print(mat_a * mat_b)

##### Lab: 넘파이 배열 슬라이싱

In [ ]:
import numpy as np 
 
x = np.array([[1.83, 1.76, 1.69, 1.86, 1.77, 1.73], 
              [86.0, 74.0, 59.0, 95.0, 80.0, 68.0]]) 
y = x[0:2, 1:3] 
z = x[0:2][1:3]

print(x)
print(y)
print(z)

print('x shape :', x.shape)
print('y shape :', y.shape)
print('z shape :', z.shape)
print('z values = :', z)

#bmi = x[0] / x[1]**2
bmi = x[1] / x[0]**2
print('BMI data')
print(bmi)

##### Lab: 2차원 배열에서 특정 조건에 맞는 행 추출

In [ ]:
import numpy as np 

players = [[170, 76.4], 
           [183, 86.2], 
           [181, 78.5], 
           [176, 80.1]] 

np_players = np.array(players) 

print('몸무게가 80 이상인 선수 정보');
print(np_players[np_players[:, 1] >= 80.0])

print('키가 180 이상인 선수 정보');
print(np_players[np_players[:, 0] >= 180.0])

#### arange()와 range() 함수 비교

In [ ]:
import numpy as np 
np.arange(5)

In [ ]:
np.arange(1, 6)

In [ ]:
np.arange(1, 10, 2)

In [ ]:
# range()를 통해 생성한 것은 반복 가능 객체

print(list(range(5)))
np.array(range(5))

In [ ]:
list(range(0, 5, 2))

In [ ]:
list(range(5))  # range()를 이용한 리스트 생성

In [ ]:
np.array(range(5))  # range()를 이용한 배열 생성

#### linspace(), logspace() 함수

In [ ]:
np.linspace(0, 10, 100)

In [ ]:
np.logspace(0, 2, 10)

#### reshape() 함수

In [ ]:
import numpy as np
y = np.arange(12) 
y.shape
y

In [ ]:
y.reshape(4, 3)

In [ ]:
y.reshape(6, -1)

In [ ]:
y.reshape(-1, 3)

In [ ]:
y.reshape(7, 2)

In [ ]:
y.flatten()

#### 난수 생성

In [ ]:
np.random.seed(10)

In [ ]:
np.random.rand(5)   # 0부터 1사이의 균일 분포에서 난수 배열 생성

In [ ]:
np.random.rand(5, 3)

In [ ]:
# 10에서 20사이의 난수 5개 생성
a = 10
b = 20 
(b - a) * np.random.rand(5) + a

In [ ]:
np.random.randint(1, 7, size=15)   # 균일 분포의 정수 난수 생성

In [ ]:
np.random.randint(1, 11, size=(4, 7))

#### 정규 분포의 난수 생성

In [ ]:
np.random.randn(15)

In [ ]:
np.random.randn(5, 4)

In [ ]:
mu = 10
sigma = 2
randoms = mu + sigma * np.random.randn(5, 4)
randoms

In [ ]:
# Lab: 잡음이 포함된 직선 그리기
import numpy as np
import matplotlib.pyplot as plt

pure = np.linspace(1, 10, 100)
#noise = np.random.normal(0, 1, 100)
noise = 0.5*np.random.normal(0, 1, 100)
#noise = 0.5*np.random.randn(100)

signal = pure + noise
print(signal)

plt.plot(pure, signal)
#plt.plot(signal)
plt.show()

In [ ]:
# 히스토그램
import numpy as np
import matplotlib.pyplot as plt

#numbers = np.random.normal(size=100000)
numbers = np.random.randn(10000)

plt.hist(numbers)
plt.xlabel("value")
plt.ylabel("freq")
plt.show()

In [ ]:
# Lab: 2개의 정규분포 그래프
import numpy as np
import matplotlib.pyplot as plt

m, sigma = 10, 2
Y1 = np.random.randn(10000)
Y2 = m + sigma*np.random.randn(10000)

plt.figure(figsize=(6, 4))   # 그래프 크기 설정
plt.hist(Y1, bins=20)
plt.hist(Y2, bins=20)
plt.show()

In [ ]:
# Lab: 싸인 함수 그리기
import numpy as np
import matplotlib.pyplot as plt

X = np.linspace(-2*np.pi, 2*np.pi, 100)

Y1 = np.sin(X)
Y2 = 3*np.sin(X)

plt.plot(X, Y1, X, Y2)
plt.show()

In [ ]:
# Lab: MSE 오차 계산
import numpy as np

ypred = np.array([1, 0, 0, 0, 0])
y = np.array([0, 1, 0, 0, 0])

n = 5
MSE = (1/n)*np.sum(np.square(ypred-y))
print(MSE)

#### 평균과 중간값 계산하기

In [ ]:
m = 175 
sigma = 10 
heights = m + sigma*np.random.randn(10000)
print(heights)

In [ ]:
np.mean(heights)

In [ ]:
np.median(heights)

In [ ]:
array_data = np.array([3, 7, 1, 2, 21])
np.mean(array_data)

In [ ]:
np.median(array_data)  # 이상치의 영향을 덜 받는다.

##### Lab: 평균과 중간값 계산하기

In [ ]:
import numpy as np 
 
players = np.zeros((100, 3))
#print(players)
players[:, 0] = 10 * np.random.randn(100) + 175 
players[:, 1] = 10 * np.random.randn(100) + 70
players[:, 2] = np.floor(10 * np.random.randn(100)) + 22  # 나이는 정수로
#players[:, 2] = 10 * np.random.randn(100) + 22
#print(players)

heights = players[:, 0] 
print('신장 평균값:', np.mean(heights))
print('신장 중앙값:', np.median(heights))

weights = players[:, 1] 
print('체중 평균값:', np.mean(weights))
print('체중 중앙값:', np.median(weights))

ages = players[:, 2] 
print('나이 평균값:', np.mean(ages))
print('나이 중앙값:', np.median(ages))

#### 상관관계

In [ ]:
import numpy as np 

x = [i for i in range(100)]
y = [i**2 for i in range(100)]
print(x); print(y)

result = np.corrcoef(x, y)
print(result)

#### 다변수 사이의 상관관계

In [ ]:
x = [i for i in range(100)]
y = [i ** 2 for i in range(100)]
z = [100 * np.sin(3.14*i/100) for i in range(0, 100)]
print(z)

In [ ]:
result = np.corrcoef([x, y, z])
print(result)

#### 전치행렬 계산

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)

print(x.transpose())
print(x.T)

#### 역행렬 계산

In [ ]:
x = np.array([[1, 2], [3, 4]])
print(x)

y = np.linalg.inv(x)
print(y)

z = np.dot(x, y)
print(z)

#### 선형방정식 풀기

In [ ]:
a = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(a, b)
print(a); print(b)
print(x)

#### arange(), reshape(), flatten()

In [ ]:
a = np.arange(0, 24).reshape(4, 3, 2)
print(a)

In [ ]:
print(a.flatten())